function onOpen(e) {
  menu();
  SM.onOpen();
}

function menu() {

  var menu = SpreadsheetApp.getUi().createMenu('Viet')
  menu
    .addItem('load', 'load')
    .addItem('sendInv', 'sendInv')
    .addItem('export_pdf_selection', 'export_pdf_selection')
    .addSeparator()
    .addItem('goToSheetByName', 'goToSheetByName')
    .addItem('moveThisSheetNameHere', 'moveThisSheetNameHere')
    .addItem('inv_header_1003', 'inv_header_1003')
    .addSeparator()
    .addItem('fillRetouch1', 'fillRetouch1')
    .addItem('fillRetouchList', 'fillRetouchList')
    .addSeparator()
    .addItem('toArchiveList', 'toArchiveList')
    .addItem('fromArchiveSelected', 'getSheetsFromArchiveSelected')
    .addSeparator()
    .addItem('newClientList', 'newClientList')
    .addItem('note2', 'note2')
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('PDF')
      .addItem('generatePdf_1', 'generatePdf_1')
      .addItem('generatePdf_all', 'generatePdf_all'))
    .addItem('generatePdfList', 'generatePdfList')
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Empty Column')
      .addItem('hideEmptyCols', 'hideEmptyCols')
      .addItem('hideEmptyColsBatch2', 'hideEmptyColsBatch2')
      .addSeparator()
      .addItem('unHideEmptyCol_1', 'unHideEmptyCol_1')
      .addItem('unHideEmptyCol_all', 'unHideEmptyCol_all')
    )
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Index')
      .addItem('getIndex', 'getIndex')
      .addItem('moveSheetByIndex', 'moveSheetByIndex'))
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Retouch')
      .addItem('retouch_fill_all', 'retouch_fill_all')
      .addItem('retouchConvertToValueBatch', 'retouchConvertToValueBatch')
      .addItem('retouchConvertToValue', 'retouchConvertToValue')
    )
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Others')
      .addItem('empty_inv_all', 'empty_inv_all')
      .addItem('removeTabColorList', 'removeTabColorList')
      .addItem('getLinks', 'getLinks')
      .addItem('moveSheetsToArchiveSelected', 'moveSheetsToArchiveSelected')
      .addItem('columnWithAll', 'columnWithAll')
      .addItem('fixJW', 'fixJW')
      .addItem('getSheetLink', 'getSheetLink')
      .addItem('empty_inv_list', 'empty_inv_list')
    )
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Batch')
      .addItem('moneyBatch', 'moneyBatch')
      .addItem('generatePdf_all', 'generatePdf_all')
    )
  menu.addItem('copyNewJW', 'copyNewJW')
    .addToUi();
}